### ISSUE TITLE
Question: Scoreboard as economy system

### ISSUE THREAD

**Issue by BrewDawg12** [nahkd123/stonks#53]
How do you make it so a score on a scoreboard is the $ on the market?

**Comment by nahkd123** [comment]
If I understand your question correctly, you are trying to use scoreboard score as money for Stonks.

Open `config/stonks/config` in plain text editor and add new scoreboard economy adapter, which is described in https://nahkd123.github.io/stonks/References/Adapters/ScoreboardEconomyAdapter/

For example, to use `playerBalance` objective for economy:

```
useAdapter stonks.fabric.adapter.provided.ScoreboardEconomyAdapter
    objective playerBalance

    // Decimal points (Eg: 2 decimal points means 200 score == $2.00)
    decimals 2
```

**Comment by BrewDawg12** [comment]
@nahkd123 Thank You, Great Mod By The Way
