### ISSUE TITLE
How to use ScoreboardEconomy Adapter?

### ISSUE THREAD

**Issue by pikmin6000** [nahkd123/stonks#57]
Hello, I tried using the ScoreboardEconomyAdapter and while using /stonks inspect @s would give the correct balance, when I do /market the various items for sale don't show up properly (they display as barrier blocks and I am unable to make a sell offer as the mod doesn't recognize me as having the item in my inventory).

I am using stonks fabric 2.0.5 for minecraft 1.20.5.

**Comment by nahkd123** [comment]
Does it works if you use the give command from Stonks? The command is `/stonks give` if I remembered correctly.

**Comment by pikmin6000** [comment]
When I do /stonks give \@s steak 1 the server says "Gave <username> 1x Steak" but I don't actually receive any items.

**Comment by nahkd123** [comment]
> When I do /stonks give \@s steak 1 the server says "Gave <username> 1x Steak" but I don't actually receive any items.

Can you share the configuration file here?

**Comment by pikmin6000** [comment]
https://pastebin.com/rvTjykdV

**Comment by nahkd123** [comment]
Can you try Stonks for 1.21/1.21.1? It still give me the item when using `/stonks give` command.

Additionally, can you give me your mods list so I can try reproducing the issue?

**Comment by pikmin6000** [comment]
I get the same issue when I try 1.21. The only mods I'm using are fabric api and stonks fabric (file names fabric-api-0.102.0+1.21.jar and stonks-fabric-2.1.0+1.21.jar).

**Comment by nahkd123** [comment]
```diff
  // Adapters
+ useAdapter stonks.fabric.adapter.provided.ItemsAdapter
  useAdapter stonks.fabric.adapter.provided.ScoreboardEconomyAdapter
      // Name of scoreboard objective you want to use
      // If the objective doesn't exists, it will creates a new "dummy" objective
```

Add `stonks.fabric.adapter.provided.ItemsAdapter` so that Stonks can recognize the items.

**Comment by pikmin6000** [comment]
Oh, I didn't realize that was necessary when using the scoreboard adapter. Thank you for the help, the issue has been resolved.
