### ISSUE TITLE
How to compile from source?

### ISSUE THREAD

**Issue by pikmin6000** [nahkd123/stonks#59]
Hello,

I tried running ./gradlew (on Linux) after downloading the repository, but it seems I may need more files to be able to make the .jar properly. Is there anything else I should add to be able to generate the .jar?

**Comment by nahkd123** [comment]
You have to use `./gradlew build`, then grab the jar in `stonks-fabric/build/libs`. You can check out the actions workflow file to see how it automatically build the jar.

**Comment by pikmin6000** [comment]
When I do ./gradlew build I get the following:

`Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :
Stonks2 - Version 2.0.0+1.20.1

> Configure project :fabric
Fabric Loom: 1.3.10
Path for java installation '/usr/lib/jvm/openjdk-11' (Common Linux Locations) does not contain a java executable
Path for java installation '/usr/lib/jvm/openjdk-17' (Common Linux Locations) does not contain a java executable
Path for java installation '/usr/lib/jvm/openjdk-21' (Common Linux Locations) does not contain a java executable
:remapping 44 mods from modImplementation (java-api)
:remapping sources
Status ERROR: org.cadixdev.mercury.shadow.org.eclipse.jdt.core code=4 Could not retrieve declared methods org.cadixdev.mercury.shadow.org.eclipse.jdt.internal.compiler.problem.AbortCompilation: Pb(347) The type javax.annotation.Nullable cannot be resolved. It is indirectly referenced from required type com.mojang.serialization.Dynamic
Could not remap sgui-1.2.2+1.20-sources.jar fully!`

**Comment by nahkd123** [comment]
Are you trying to build with commit https://github.com/nahkd123/stonks/tree/14daa2cdafb29905c822d7f9f298365de9772e3b? I'm not sure what went wrong but GH actions still build my mod successfully. You can take a look at workflow file (https://github.com/nahkd123/stonks/actions/runs/5941876964/workflow) to see the entire build process. I suggest try building in brand new Ubuntu container with Java 17. `gradle/gradle-build-action` is just a wrapper for `./gradlew` but with caching to speed up the builds.

**Comment by nahkd123** [comment]
I was able to build Stonks in Ubuntu container:

```sh
# Run a new container with ubuntu:latest image
docker pull ubuntu
docker run -i -t --entrypoint bash ubuntu

# Inside container
cd
apt update
apt install git openjdk-17-jre
git clone https://github.com/nahkd123/stonks.git
cd stonks
git checkout v2.0.2+1.20.1
./gradlew build
exit

# Outside container
docker cp 61efc43b4d38:/root/stonks/fabric/build/libs ~/stonks-fabric-files
```

**Comment by pikmin6000** [comment]
I made a new VM and after running `./gradlew build` (and waiting 5 minutes for the build) the message `BUILD SUCCESSFUL` appeared, but the .jar that was generated was empty except for the META-INF file.

**Comment by nahkd123** [comment]
> I made a new VM and after running `./gradlew build` (and waiting 5 minutes for the build) the message `BUILD SUCCESSFUL` appeared, but the .jar that was generated was empty except for the META-INF file.

Are you sure you are getting the correct jar file? Stonks for Fabric is located in `fabric/build/libs/stonks-fabric-2.0.0+1.21.1.jar`.

**Comment by pikmin6000** [comment]
Oh, I was checking build/ instead of fabric/build/. After checking the correct location, it does seem that the .jar built correctly. Thank you.
