### ISSUE TITLE
Bug: Using the ScoreboardEconomyAdapter im unable to add balance to the person selling items

### ISSUE THREAD

**Issue by Schnullie** [nahkd123/stonks#64]
When i create a sell offer, im able to do that. My items get subtracted from my inventory, and other people on my server are able to buy them. When they buy my items, their balance gets subtraced, but the player selling the items won't get any balance added to their account.

**Comment by nahkd123** [comment]
Have you claimed the offer from player's offers list yet? You have to claim it in order to get the money.

**Comment by Schnullie** [comment]
Yes, claiming the buy offer works. Thanks for the quick reply.
